apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: korrel8r
  name: korrel8rs.korrel8r.openshift.io
spec:
  group: korrel8r.openshift.io
  names:
    kind: Korrel8r
    listKind: Korrel8rList
    plural: korrel8rs
    singular: korrel8r
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Korrel8r is a service that correlates observabililty signals
          in the cluster.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Korrel8rSpec defines the desired state of Korrel8r
            properties:
              config:
                description: "Config is the configuration for a korrel8r deployment.
                  If not provided there is a default configuration suitable for use
                  in an openshift cluster. \n The \"include\" section can load additional
                  configuration files provided at /etc/korrel8r"
                properties:
                  groups:
                    description: Groups defines short names for groups of related
                      classes.
                    items:
                      description: Group of similar classes that can be referred to
                        by a short name in a ClassSpec.
                      properties:
                        classes:
                          description: Classes are the names of classes in this group.
                          items:
                            type: string
                          type: array
                        domain:
                          description: Domain of the classes, all must be in the same
                            domain.
                          type: string
                        name:
                          description: Name is the short name for a group of classes.
                          type: string
                      required:
                      - classes
                      - domain
                      - name
                      type: object
                    type: array
                  include:
                    description: Include lists additional configuration files or URLs
                      to include.
                    items:
                      type: string
                    type: array
                  rules:
                    description: Rules define the relationships that korrel8r will
                      follow.
                    items:
                      description: Rule specifies a template rule. It generates one
                        or more korrel8r.Rule.
                      properties:
                        goal:
                          description: Goal specifies the set of classes that this
                            rule can produce.
                          properties:
                            classes:
                              description: Classes is a list of class names to be
                                selected from the domain. If absent, all classes in
                                the domain are selected.
                              items:
                                type: string
                              type: array
                            domain:
                              description: Domain is the domain for selected classes.
                              type: string
                          required:
                          - domain
                          type: object
                        name:
                          description: Name is a short, descriptive name. If omitted,
                            a name is generated from Start and Goal.
                          type: string
                        result:
                          description: TemplateResult contains templates to generate
                            the result of applying this rule. Each template is applied
                            to an object from one of the `start` classes. If any template
                            yields a blank string or an error, the rule does not apply.
                          properties:
                            constraint:
                              description: Constraint template is optional, it generates
                                a korrel8r.Constraint in JSON form. This constraint
                                is combined with the constraint already in force,
                                if there is one. See Constraint.Combine
                              type: string
                            query:
                              description: Query template generates a query object
                                suitable for the goal store.
                              type: string
                          required:
                          - query
                          type: object
                        start:
                          description: Start specifies the set of classes that this
                            rule can apply to.
                          properties:
                            classes:
                              description: Classes is a list of class names to be
                                selected from the domain. If absent, all classes in
                                the domain are selected.
                              items:
                                type: string
                              type: array
                            domain:
                              description: Domain is the domain for selected classes.
                              type: string
                          required:
                          - domain
                          type: object
                      required:
                      - goal
                      - result
                      - start
                      type: object
                    type: array
                  stores:
                    description: Stores is a list of store configurations.
                    items:
                      additionalProperties:
                        type: string
                      description: StoreConfig is a map of name:value attributes used
                        to connect to a store. The names and values depend on the
                        type of store.
                      type: object
                    type: array
                type: object
              verbose:
                description: Verbose sets the numeric logging verbosity for the KORREL8R_VERBOSE
                  environment variable.
                type: integer
            type: object
          status:
            description: Korrel8rStatus defines the observed state of Korrel8r
            properties:
              conditions:
                description: Conditions conditions.type is one of "Available", "Progressing",
                  and "Degraded"
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource. --- This struct is intended for direct
                    use as an array at the field path .status.conditions.  For example,
                    \n type FooStatus struct{ // Represents the observations of a
                    foo's current state. // Known .status.conditions.type are: \"Available\",
                    \"Progressing\", and \"Degraded\" // +patchMergeKey=type // +patchStrategy=merge
                    // +listType=map // +listMapKey=type Conditions []metav1.Condition
                    `json:\"conditions,omitempty\" patchStrategy:\"merge\" patchMergeKey:\"type\"
                    protobuf:\"bytes,1,rep,name=conditions\"` \n // other fields }"
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition
                        transitioned from one status to another. This should be when
                        the underlying condition changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating
                        the reason for the condition's last transition. Producers
                        of specific condition types may define expected values and
                        meanings for this field, and whether the values are considered
                        a guaranteed API. The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        --- Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
