---
catalog_templates:
  - template_name: v4.16.yaml
    channels: [stable]
    replaces: multicluster-global-hub-operator.v1.5.0
  - template_name: v4.17.yaml
    channels: [stable]
    replaces: multicluster-global-hub-operator.v1.5.0
  - template_name: v4.18.yaml
    channels: [stable]
    replaces: multicluster-global-hub-operator.v1.5.0
  - template_name: v4.19.yaml
    channels: [stable]
    replaces: multicluster-global-hub-operator.v1.5.0
  - template_name: v4.20.yaml
    channels: [stable]
