---
# Source: release-config/templates/release-config.yaml
catalog_templates:
  - template_name: v4.17.yaml
    channels: [stable]
    replaces: dell-csm-operator.v1.10.1
    skips:
      - dell-csm-operator.v1.11.0
      - dell-csm-operator.v1.11.1
  - template_name: v4.18.yaml
    channels: [stable]
    replaces: dell-csm-operator.v1.10.1
    skips:
      - dell-csm-operator.v1.11.0
      - dell-csm-operator.v1.11.1
  - template_name: v4.19.yaml
    channels: [stable]
    replaces: dell-csm-operator.v1.10.1
    skips:
      - dell-csm-operator.v1.11.0
      - dell-csm-operator.v1.11.1
  - template_name: v4.20.yaml
    channels: [stable]
    replaces: dell-csm-operator.v1.10.1
    skips:
      - dell-csm-operator.v1.11.0
      - dell-csm-operator.v1.11.1
