apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: amp-gpu
    app.kubernetes.io/name: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
    control-plane: controller-manager
  name: amd-gpu-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: amp-gpu
    app.kubernetes.io/name: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
    control-plane: controller-manager
status:
  loadBalancer: {}
