apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  creationTimestamp: null
  name: servicemeshes.services.platform.opendatahub.io
spec:
  group: services.platform.opendatahub.io
  names:
    kind: ServiceMesh
    listKind: ServiceMeshList
    plural: servicemeshes
    singular: servicemesh
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Ready
      jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - description: Reason
      jsonPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ServiceMesh is the Schema for the servicemesh API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              auth:
                description: |-
                  Auth holds configuration of authentication and authorization services
                  used by Service Mesh in Opendatahub.
                properties:
                  audiences:
                    default:
                    - https://kubernetes.default.svc
                    description: |-
                      Audiences is a list of the identifiers that the resource server presented
                      with the token identifies as. Audience-aware token authenticators will verify
                      that the token was intended for at least one of the audiences in this list.
                      If no audiences are provided, the audience will default to the audience of the
                      Kubernetes apiserver (kubernetes.default.svc).
                    items:
                      type: string
                    type: array
                  namespace:
                    description: |-
                      Namespace where it is deployed. If not provided, the default is to
                      use '-auth-provider' suffix on the ApplicationsNamespace of the DSCI.
                    maxLength: 63
                    pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?)?$
                    type: string
                type: object
              controlPlane:
                description: |-
                  servicemesh spec exposed to DSCI api
                  ControlPlane holds configuration of Service Mesh used by Opendatahub.
                properties:
                  metricsCollection:
                    default: Istio
                    description: |-
                      MetricsCollection specifies if metrics from components on the Mesh namespace
                      should be collected. Setting the value to "Istio" will collect metrics from the
                      control plane and any proxies on the Mesh namespace (like gateway pods). Setting
                      to "None" will disable metrics collection.
                    enum:
                    - Istio
                    - None
                    type: string
                  name:
                    default: data-science-smcp
                    description: Name is a name Service Mesh Control Plane. Defaults
                      to "data-science-smcp".
                    type: string
                  namespace:
                    default: istio-system
                    description: Namespace is a namespace where Service Mesh is deployed.
                      Defaults to "istio-system".
                    maxLength: 63
                    pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?)?$
                    type: string
                type: object
              managementState:
                default: Removed
                enum:
                - Managed
                - Unmanaged
                - Removed
                pattern: ^(Managed|Unmanaged|Force|Removed)$
                type: string
            type: object
          status:
            description: ServiceMeshStatus defines the observed state of ServiceMesh
            properties:
              conditions:
                items:
                  properties:
                    lastHeartbeatTime:
                      description: |-
                        The last time we got an update on a given condition, this should not be set and is
                        present only for backward compatibility reasons
                      format: date-time
                      type: string
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.
                        If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human-readable message indicating
                        details about the transition.
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        The value should be a CamelCase string.
                      type: string
                    severity:
                      description: |-
                        Severity with which to treat failures of this type of condition.
                        When this is not specified, it defaults to Error.
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-type: atomic
              observedGeneration:
                description: The generation observed by the resource controller.
                format: int64
                type: integer
              phase:
                type: string
            type: object
        type: object
        x-kubernetes-validations:
        - message: ServiceMesh name must be default-servicemesh
          rule: self.metadata.name == 'default-servicemesh'
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
