apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: prometheus-operator-admission-webhook
    app.kubernetes.io/part-of: observability-operator
    app.kubernetes.io/version: 0.69.0-rhobs1
  name: obo-prometheus-operator-admission-webhook
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/name: prometheus-operator-admission-webhook
    app.kubernetes.io/part-of: observability-operator
status:
  loadBalancer: {}
