catalog_templates:
- template_name: 4.17.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.2
- template_name: 4.18.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.2
- template_name: 4.19.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.2
- template_name: 4.20.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.2
- template_name: 4.21.yaml
  channels:
  - stable
  replaces: rabbitmq-messaging-topology-operator.v1.18.2
