apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  labels:
    app: 3scale-api-management
  name: apimanagerrestores.apps.3scale.net
spec:
  group: apps.3scale.net
  names:
    kind: APIManagerRestore
    listKind: APIManagerRestoreList
    plural: apimanagerrestores
    singular: apimanagerrestore
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: APIManagerRestore represents an APIManager restore
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: APIManagerRestoreSpec defines the desired state of APIManagerRestore
            properties:
              restoreSource:
                description: APIManagerRestoreSource defines the backup data restore source configurability. It is a union type. Only one of the fields can be set
                properties:
                  persistentVolumeClaim:
                    description: Restore data soure configuration
                    properties:
                      claimSource:
                        description: PersistentVolumeClaim source of an existing PersistentVolumeClaim. See
                        properties:
                          claimName:
                            description: 'claimName is the name of a PersistentVolumeClaim in the same namespace as the pod using this volume. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims'
                            type: string
                          readOnly:
                            description: readOnly Will force the ReadOnly setting in VolumeMounts. Default false.
                            type: boolean
                        required:
                        - claimName
                        type: object
                    required:
                    - claimSource
                    type: object
                type: object
            required:
            - restoreSource
            type: object
          status:
            description: APIManagerRestoreStatus defines the observed state of APIManagerRestore
            properties:
              apiManagerToRestoreRef:
                description: Name of the APIManager to be restored
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              completed:
                description: Set to true when backup has been completed
                type: boolean
              completionTime:
                description: Restore completion time. It is represented in RFC3339 form and is in UTC.
                format: date-time
                type: string
              mainStepsCompleted:
                description: Set to true when main steps have been completed. At this point restore still cannot be considered fully completed due to some remaining post-backup tasks are pending (cleanup, ...)
                type: boolean
              startTime:
                description: Restore start time. It is represented in RFC3339 form and is in UTC.
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
