apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  labels:
    app: 3scale-api-management
  name: activedocs.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: ActiveDoc
    listKind: ActiveDocList
    plural: activedocs
    singular: activedoc
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.providerAccountHost
      name: Provider Account
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - jsonPath: .status.activeDocId
      name: 3scale ID
      type: integer
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: ActiveDoc is the Schema for the activedocs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ActiveDocSpec defines the desired state of ActiveDoc
            properties:
              activeDocOpenAPIRef:
                description: ActiveDocOpenAPIRef Reference to the OpenAPI Specification
                oneOf:
                - required:
                  - secretRef
                - required:
                  - url
                properties:
                  secretRef:
                    description: SecretRef refers to the secret object that contains the OpenAPI Document
                    properties:
                      apiVersion:
                        description: API version of the referent.
                        type: string
                      fieldPath:
                        description: 'If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: "spec.containers{name}" (where "name" refers to the name of the container that triggered the event) or if no container name is specified "spec.containers[2]" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object. TODO: this design is not final and this field is subject to change in the future.'
                        type: string
                      kind:
                        description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                        type: string
                      name:
                        description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                        type: string
                      namespace:
                        description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                        type: string
                      resourceVersion:
                        description: 'Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                        type: string
                      uid:
                        description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                        type: string
                    type: object
                    x-kubernetes-map-type: atomic
                  url:
                    description: URL Remote URL from where to fetch the OpenAPI Document
                    pattern: ^https?:\/\/.*$
                    type: string
                type: object
              description:
                description: Description is a human readable text of the activedoc
                type: string
              name:
                description: Name is human readable name for the activedoc
                type: string
              productSystemName:
                description: ProductSystemName identifies uniquely the product
                type: string
              providerAccountRef:
                description: ProviderAccountRef references account provider credentials
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              published:
                description: Published switch to publish the activedoc
                type: boolean
              skipSwaggerValidations:
                description: SkipSwaggerValidations switch to skip OpenAPI validation
                type: boolean
              systemName:
                description: SystemName identifies uniquely the activedoc within the account provider Default value will be sanitized Name
                pattern: ^[a-z0-9]+$
                type: string
            required:
            - activeDocOpenAPIRef
            - name
            type: object
          status:
            description: ActiveDocStatus defines the observed state of ActiveDoc
            properties:
              activeDocId:
                format: int64
                type: integer
              conditions:
                description: Current state of the activedoc resource. Conditions represent the latest available observations of an object's state
                items:
                  description: "Condition represents an observation of an object's state. Conditions are an extension mechanism intended to be used when the details of an observation are not a priori known or would not apply to all instances of a given Kind. \n Conditions should be added to explicitly convey properties that users and components care about rather than requiring those properties to be inferred from other observations. Once defined, the meaning of a Condition can not be changed arbitrarily - it becomes part of the API, and has the same backwards- and forwards-compatibility concerns of any other part of the API."
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      description: ConditionReason is intended to be a one-word, CamelCase representation of the category of cause of the current status. It is intended to be used in concise output, such as one-line kubectl get output, and in summarizing occurrences of causes.
                      type: string
                    status:
                      type: string
                    type:
                      description: "ConditionType is the type of the condition and is typically a CamelCased word or short phrase. \n Condition types should indicate state in the \"abnormal-true\" polarity. For example, if the condition indicates when a policy is invalid, the \"is valid\" case is probably the norm, so the condition should be called \"Invalid\"."
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: ObservedGeneration reflects the generation of the most recently observed Backend Spec.
                format: int64
                type: integer
              productResourceName:
                description: ProductResourceName references the managed 3scale product
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              providerAccountHost:
                description: ProviderAccountHost contains the 3scale account's provider URL
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
