catalog_templates:
  - template_name: v4.12-v4.16.yaml
    channels: [beta]
    replaces: victoriametrics-operator.v0.60.2
  - template_name: latest.yaml
    channels: [beta]
    replaces: victoriametrics-operator.v0.60.2
