---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: coherence-operator
    app.kubernetes.io/version: 3.5.7
    control-plane: coherence
  name: coherence-operator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/component: manager
    app.kubernetes.io/instance: coherence-operator-manager
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/version: 3.5.7
    control-plane: coherence
status:
  loadBalancer: {}
