catalog_templates:
- template_name: v4.17.yaml
  channels:
  - stable
  replaces: rabbitmq-cluster-operator.v2.18.0
- template_name: v4.18.yaml
  channels:
  - stable
  replaces: rabbitmq-cluster-operator.v2.18.0
- template_name: v4.19.yaml
  channels:
  - stable
  replaces: rabbitmq-cluster-operator.v2.18.0
- template_name: v4.20.yaml
  channels:
  - stable
  replaces: rabbitmq-cluster-operator.v2.18.0
