---
catalog_templates:
  - template_name: v4.16.yaml
    channels: release-1.7
  - template_name: v4.17.yaml
    channels: release-1.7
  - template_name: v4.18.yaml
    channels: release-1.7
  - template_name: v4.19.yaml
    channels: release-1.7
  - template_name: v4.20.yaml
    channels: release-1.7
  - template_name: v4.21.yaml
    channels: release-1.7
