apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: aws-neuron
    app.kubernetes.io/name: aws-neuron
    app.kubernetes.io/part-of: aws-neuron
  name: awslabs-gpu-operator-node-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awslabs-gpu-operator-node-metrics
subjects:
- kind: ServiceAccount
  name: awslabs-gpu-operator-node-metrics
  namespace: ai-operator-on-aws
