apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: coherence-operator-webhook
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/part-of: coherence-operator
    app.kubernetes.io/version: 3.4.3
    control-plane: coherence
  name: coherence-operator-webhook
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: webhook-server
  selector:
    app.kubernetes.io/component: manager
    app.kubernetes.io/instance: coherence-operator-manager
    app.kubernetes.io/name: coherence-operator
    app.kubernetes.io/version: 3.4.3
    control-plane: coherence
status:
  loadBalancer: {}
