aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.konflux-ci.dev/aggregate-to-viewer: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  creationTimestamp: null
  name: konflux-viewer-user-actions
rules: []
