apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: konflux-operator
  name: konflux-operator-konfluxui-viewer-role
rules:
- apiGroups:
  - konflux.konflux-ci.dev
  resources:
  - konfluxuis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konflux.konflux-ci.dev
  resources:
  - konfluxuis/status
  verbs:
  - get
