catalog_templates:
  - template_name: v4.19.yaml
    channels: [Fast, Stable]
    replaces: aws-neuron-operator.v0.0.2
  - template_name: v4.20.yaml
    channels: [Fast, Stable]
    replaces: aws-neuron-operator.v0.0.2
