apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ossmconsoles.kiali.io
  labels:
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
spec:
  group: kiali.io
  names:
    kind: OSSMConsole
    listKind: OSSMConsoleList
    plural: ossmconsoles
    singular: ossmconsole
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
