production:
  type: ocp
  bundle:
    registry: quay.io
    organization: openshift-community-operators
  index:
    registry: quay.io
    organisation: openshift-community-operators
    name: catalog
    tags:
      - v4.6
      - v4.7
      - v4.8
    latest: v4.6
  mirror:
    multiarch:
      enabled: true
      registry: quay.io
      organisation: redhat
      name: redhat----community-operator-index

testing:
    test_script_url: https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/test.sh
    iss_script_url: https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/iss.sh
    image: quay.io/operator_testing/operator-test-playbooks:latest

operatorhubio:
  enabled: false
#base:
#  organisation: operator-framework
#  project: operator-test-playbooks
#  tag: master
tools:
  kind_version: v0.9.0
  kind_kube_version: v1.21.1
  operator_sdk_version: v1.8.0
#  operator_courier_version: 2.1.11
#  olm_version: 0.17.0
#  opm_version: v1.17.0
#  oc_version: 4.3.5
#  go_version: 1.13.7
#  jq_version: 1.6
#  yq_version: 2.2.1
#  umoci_version: v0.4.5