apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: konflux-operator
  name: konflux-operator-konfluximagecontroller-admin-role
rules:
- apiGroups:
  - konflux.konflux-ci.dev
  resources:
  - konfluximagecontrollers
  verbs:
  - '*'
- apiGroups:
  - konflux.konflux-ci.dev
  resources:
  - konfluximagecontrollers/status
  verbs:
  - get
