aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.konflux-ci.dev/aggregate-to-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  creationTimestamp: null
  name: konflux-admin-user-actions
rules: []
