aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.konflux-ci.dev/aggregate-to-maintainer: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: konflux-maintainer-user-actions
rules: []
