---
catalog_templates:
  - template_name: v4.12.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.13.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.14.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.15.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.16.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.17.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.18.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.19.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.20.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
  - template_name: v4.21.yaml
    channels: [fast]
    replaces: patterns-operator.v0.0.63
