---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  creationTimestamp: null
  name: openstacklightspeeds.lightspeed.openstack.org
spec:
  group: lightspeed.openstack.org
  names:
    kind: OpenStackLightspeed
    listKind: OpenStackLightspeedList
    plural: openstacklightspeeds
    singular: openstacklightspeed
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status
      jsonPath: .status.conditions[0].status
      name: Status
      type: string
    - description: Message
      jsonPath: .status.conditions[0].message
      name: Message
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: OpenStackLightspeed is the Schema for the openstacklightspeeds
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: OpenStackLightspeedSpec defines the desired state of OpenStackLightspeed
            properties:
              catalogSourceName:
                default: redhat-operators
                description: Name of the CatalogSource that contains the OLS Operator
                type: string
              catalogSourceNamespace:
                default: openshift-marketplace
                description: Namespace where the CatalogSource containing the OLS
                  operator is located
                type: string
              enableOCPRAG:
                default: false
                description: Enables automatic OCP documentation based on cluster
                  version
                type: boolean
              feedbackDisabled:
                description: Disable feedback collection
                type: boolean
              llmAPIVersion:
                description: LLM API Version for LLM providers that require it (e.g.,
                  Microsoft Azure OpenAI)
                type: string
              llmCredentials:
                description: |-
                  Secret name containing API token for the LLMEndpoint. The secret must contain
                  a field named "apitoken" which holds the token value.
                type: string
              llmDeploymentName:
                description: Deployment name for LLM providers that require it (e.g.,
                  Microsoft Azure OpenAI)
                type: string
              llmEndpoint:
                description: URL pointing to the LLM
                type: string
              llmEndpointType:
                description: Type of the provider serving the LLM
                enum:
                - azure_openai
                - bam
                - openai
                - watsonx
                - rhoai_vllm
                - rhelai_vllm
                - fake_provider
                type: string
              llmProjectID:
                description: Project ID for LLM providers that require it (e.g., WatsonX)
                type: string
              maxTokensForResponse:
                description: MaxTokensForResponse defines the maximum number of tokens
                  to be used for the response generation
                type: integer
              modelName:
                description: Name of the model to use at the API endpoint provided
                  in LLMEndpoint
                type: string
              ocpVersionOverride:
                description: |-
                  Allows forcing a specific OCP version instead of auto-detection.
                  Format should be like "4.15", "4.16", etc.
                type: string
              ragImage:
                description: ContainerImage for the OpenStack Lightspeed RAG container
                  (will be set to environmental default if empty)
                type: string
              tlsCACertBundle:
                description: Configmap name containing a CA Certificates bundle
                type: string
              transcriptsDisabled:
                description: Disable conversation transcripts collection
                type: boolean
            required:
            - llmCredentials
            - llmEndpoint
            - llmEndpointType
            - modelName
            type: object
          status:
            description: OpenStackLightspeedStatus defines the observed state of OpenStackLightspeed
            properties:
              activeOCPRAGVersion:
                description: |-
                  ActiveOCPRAGVersion contains the OCP version being used for RAG configuration
                  Will be one of: "4.16", "4.18", "latest", or empty if OCP RAG is disabled
                type: string
              conditions:
                description: Conditions
                items:
                  description: Condition defines an observation of a API resource
                    operational state.
                  properties:
                    lastTransitionTime:
                      description: |-
                        Last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed. If that is not known, then using the time when
                        the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase.
                      type: string
                    severity:
                      description: |-
                        Severity provides a classification of Reason code, so the current situation is immediately
                        understandable and could act accordingly.
                        It is meant for situations where Status=False and it should be indicated if it is just
                        informational, warning (next reconciliation might fix it) or an error (e.g. DB create issue
                        and no actions to automatically resolve the issue can/should be done).
                        For conditions where Status=Unknown or Status=True the Severity should be SeverityNone.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase.
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: ObservedGeneration - the most recent generation observed
                  for this object.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
