
name: Operator index sha sync

on: 
  workflow_dispatch:
    inputs:
      kubernetes:
        description: 'Sync index sha for kuberentes'     
        required: true
        default: '0'
      openshift:
        description: 'Sync index sha for openshift'     
        required: true
        default: '0'

env:
  OPP_CONTAINER_OPT: "-t"
  OPP_SCRIPT_ISS_URL: "https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp-iss.sh"
  GODEBUG: x509ignoreCN=0
  OPP_INDEX_MIRROR: 1
  OPP_MIRROR_LATEST_TAG: "v4.6"
  OPP_PRODUCTION_TYPE: "ocp"
  OPP_MIRROR_INDEX_MULTIARCH_BASE: "registry.redhat.io/openshift4/ose-operator-registry"
  OPP_MULTIARCH_SUPPORTED_VERSIONS: "v4.5 v4.6 v4.7 v4.8 v4.9 v4.10 v4.11 v4.12"
  OPP_MIRROR_INDEX_MULTIARCH_POSTFIX: "s"
  OPP_MIRROR_INDEX_REGISTRY: "quay.io"
  OPP_MIRROR_INDEX_ORGANIZATION: "redhat"
  OPP_MIRROR_INDEX_NAME: "redhat----community-operator-index"
  IIB_INPUT_REGISTRY_USER: "12742415|community-operators-pipeline"
  OPP_REGISTRY_MIRROR_USER: "redhat+iib_community"

  #QUAY_API_TOKEN_OPENSHIFT_COMMUNITY_OP: ${{ secrets.QUAY_API_TOKEN_OPENSHIFT_COMMUNITY_OP }}
  #QUAY_API_TOKEN_OPERATORHUBIO: ${{ secrets.QUAY_API_TOKEN_OPERATORHUBIO }}
  #QUAY_RH_INDEX_PW: ${{ secrets.QUAY_RH_INDEX_PW }}
  REGISTRY_MIRROR_PW: ${{ secrets.REGISTRY_MIRROR_PW }}
  IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}

jobs:
  k8s-index-sha:
    if: github.event.inputs.kubernetes == '1'
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    steps:
    - run: |
        echo "kubernetes: ${{ github.event.inputs.kubernetes }} latest"
        bash <(curl -sL $OPP_SCRIPT_ISS_URL) kubernetes latest

  o7t-index-sha:
    if: github.event.inputs.openshift == '1'
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    strategy:
      matrix:
        index-tag: [ v4.10-db, v4.11, v4.12, v4.13, v4.14-rc ]

      fail-fast: false
    steps:
    - run: |
        echo "openshift: ${{ github.event.inputs.openshift }} ${{ matrix.index-tag }}"
        bash <(curl -sL $OPP_SCRIPT_ISS_URL) openshift ${{ matrix.index-tag }}
